
server:
  port: 8093
spring:
  application:
    name: bitstorm-svr-testconsumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
