
server:
  port: 8082

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitstorm-svr?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root@2023
  redis:
    host: localhost
    port: 6379
    password: root2023
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#xTimer相关配置
scheduler:
   bucketsNum: 20
   tryLockSeconds: 70
   tryLockGapMilliSeconds: 100
   successExpireSeconds: 130
   pool:
    corePoolSize: 100
    maxPoolSize: 100
    queueCapacity: 99999
    namePrefix: scheduler-


trigger:
   zrangeGapSeconds: 1
   workersNum: 10000

migrator:
   workersNum: 1000
   migrateStepMinutes: 60
   migrateTryLockMinutes: 20
   migrateSuccessExpireMinutes: 120
   timerDetailCacheMinutes: 2


