
server:
  port: 8096
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  redis:
    host: localhost
    port: 6379
    password: root2023
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数



