
server:
  port: 8081
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitstorm?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: niuge
  redis:
    host: localhost
    port: 6379
    password: niuge
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数





mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
